# --------------
# -- Settings --
# --------------

# If you are hosting in a sub-folder, for example: https://mlh.github.io/mlh-hackathon-boilerplate/,
# you must specify it as the baseurl
# If you hosting as a root, for example: htttps://[github username].github.io, then leave it blank
baseurl: "/hackspiration-2025"

# uncomment the next line if you are hosting as a root and not sub-folder
# for example, when runnig locally at http://127.0.0.1:4000/
# baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "https://arya2004.github.io"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.


# Let people connect & engage with you through social media.
social:
  twitter_handle: "mlsc_vit_p"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "Hackspiration 2025 | 5-6 February 2025"
  description: "Join us for Hackspiration 2025, a hackathon brought to you by Vishwakarma Institute of Technology's Microsoft Learn Student Club. Dive into Web3, Generative AI, IoT, and Cloud Computing!"
  image:       "images/mlsc-hackathon.png"

# Event information.
event:
  name:        "Hackspiration 2025"
  description: "Hackspiration 2025 is a unique hackathon uniting innovations to transform futures, hosted by Vishwakarma Institute of Technology's Microsoft Learn Student Club."
  date:        "15 - 20 April 2025"
  location:    "Hybrid (Online Worldwide + Offline in Pune, India)"

  trust_badge:
    year:   "2025"  # season year
    region: "na"    # region can be adjusted based on specific event regions
    color:  "blue"

  hero:
    links:
      - text: "Apply"
        href: "https://hackspiration-24.devfolio.co"
      - text: "Sponsor"
        href: "mailto:mlsc@vit.edu"

  about:
    description: >
      Hackspiration 2025 invites participants into a tech playground focused on Web3, Generative AI, IoT, and Cloud Computing. Join 800+ tech enthusiasts in April for workshops, networking, and exciting rewards. Don't miss out on shaping tomorrow’s tech landscape!

  # Info Sections
  info:
    sections:
      - image: "images/learn.png"
        title: "LEARN."
        description: >
          Dive into hands-on workshops and sessions on emerging tech trends like Web3, Generative AI, and more.
      - image: "images/build.png"
        title: "BUILD."
        description: >
          Join top minds to bring innovative ideas to life, leveraging cutting-edge tools and resources.
      - image: "images/inspire.png"
        title: "INSPIRE."
        description: >
          Create impactful solutions, earn rewards, and inspire others in the global hackathon community.

  # Frequently asked questions.
  faq:
    - question: "What is Hackspiration 2025?"
      answer: >
        Hackspiration 2025 is a hackathon hosted by Vishwakarma Institute of Technology's Microsoft Learn Student Club, designed to foster innovation in areas like Web3, Generative AI, IoT, and Cloud Computing.
    - question: "How much does it cost?"
      answer: >
        Nothing at all! Hackspiration 2025 is free for everyone.
    - question: "Who can participate?"
      answer: >
        Everyone is welcome—students, professionals, and tech enthusiasts from all backgrounds!
    - question: "Where is the event?"
      answer: >
        Hackspiration 2025 is a hybrid event, held online worldwide and in-person at Pune, India.
    - question: "What networking opportunities are available?"
      answer: >
        Hackspiration 2025 includes networking sessions with peers, mentors, sponsors, and industry experts, accessible both online and offline.
    - question: "Will there be any problem statements?"
      answer: >
        Specific problem statements may be released closer to the event. Most tracks are open-ended but will follow specific guidelines provided.
    - question: "Is there a referral program?"
      answer: >
        Yes! Refer friends to earn exclusive swag like t-shirts, hoodies, and more. Top referrers win exclusive Hackspiration merchandise.

  # This is the message you'll receive once you've registered.
  register:
    message: >
      Thank you for registering for Hackspiration 2025! Look out for more information closer to the event.
      
# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME